kafka:
  brokers:
    - "kafka-1:9092"
  topic: "bearer-events"
  compression: "none"
  partitions: 3
  replication-factor: 1

producer:
  sse-url: "https://stream.wikimedia.org/v2/stream/recentchange"
  user-agent: "beaver data stream study-bot"
  batch-size: 100
  flush-interval: "5s"
